### PR TITLE
feat: add global Taskfile

### PR DESCRIPTION
**Pull request by vmaerten**
The idea is to use the new `flatten` feature in Taskfile to include this one in every project

Example : https://github.com/pbstck/intake/pull/623

### CODE REVIEW

**Comment by ridwan-b** [comment]
I like the idea, the common projects will be more readable.

**Review by ridwan-b — APPROVED** [review]

**Comment by vmaerten** [comment]
To be honest, I've developped this feature, only for us :joy:

**Review by tmuzy — APPROVED** [review]
any way to overwrite/exclude some of those tasks at project level when included from this global one ?

**Comment by vmaerten** [comment]
> any way to overwrite/exclude some of those tasks at project level when included from this global one ?

@tmuzy  Nop :/  The override is a feature that is a bit complicated to implemented.
An exclusion could do the job but not currently implemented. Thanks for the idea :blush: 

At the moment, the only way to do that, is to split this taskfile into multiple and include only which one you want

**Comment by tmuzy** [comment]
> At the moment, the only way to do that, is to split this taskfile into multiple and include only which one you want

we can come back to that if the need arises :smile: not important at all just wondering. Thanks !

**Pull request merged**
